name: Documentation

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - uses: prefix-dev/setup-pixi@v0.9.4
      with:
        pixi-version: v0.41.4
        environments: doc
        frozen: false

    - name: Build documentation
      run: pixi run -e doc build-doc

    - name: Upload pages artifact
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./doc/_build/html

  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
